# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-07 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0003_auto_20170507_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='human',
            name='birthdayPlace',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='human',
            name='deathday',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='human',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='movieseriedetails',
            name='language',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='movieseriedetails',
            name='rate',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='movieseriedetails',
            name='release',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='movieseriedetails',
            name='runtime',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='movieseriedetails',
            name='videoFormat',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='rate',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='runtime',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
