# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-07 16:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0004_auto_20170507_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='season',
            old_name='episode',
            new_name='episodes',
        ),
    ]
