# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-07 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0005_auto_20170507_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='plot',
            field=models.CharField(default=None, max_length=5000),
        ),
    ]
