# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0008_auto_20170508_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='season',
            field=models.IntegerField(null=True),
        ),
    ]
