# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0009_episode_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='rate',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='movieseriedetails',
            name='rate',
            field=models.IntegerField(null=True),
        ),
    ]
