# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 17:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0010_auto_20170508_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieseriedetails',
            name='episodes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Search.Episode'),
        ),
    ]
